/* eslint-disable @typescript-eslint/no-require-imports -- executable CommonJS utility */
const { readFileSync, mkdirSync } = require('node:fs')
const { join } = require('node:path')
const { spawnSync } = require('node:child_process')
const { parse } = require('dotenv')
const root = join(__dirname, '..')
const env = parse(readFileSync(join(root, 'apps/backend/.env')))
const url = new URL(env.DATABASE_URL)
mkdirSync(join(root, '.backups'), { recursive: true })
const path = join(root, '.backups', `meal-planner-${new Date().toISOString().replace(/[:.]/g, '-')}.dump`)
const result = spawnSync(process.env.PG_DUMP || 'pg_dump', ['--format=custom', '--file', path, '--host', url.hostname, '--port', url.port || '5432', '--username', decodeURIComponent(url.username), '--dbname', url.pathname.slice(1)], { env: { ...process.env, PGPASSWORD: decodeURIComponent(url.password) }, stdio: 'inherit' })
if (result.error) console.error(result.error.message)
if (result.status !== 0) process.exit(result.status || 1)
console.log(`Резервная копия: ${path}`)
