<template>
  <div>
    <div class="mp-page-head">
      <div class="mp-page-head__meta"><span class="mp-overline">От меню до готового обеда</span><h1 class="mp-page-title">Закупки и готовка.</h1><p class="mp-page-subtitle">Целые упаковки, понятные остатки и дела на конкретный день.</p></div>
      <v-btn :to="selectedId ? `/menu?plan=${selectedId}` : '/menu'" variant="outlined"><MpIcon name="calendar" :size="17" />Исходное меню</v-btn>
    </div>
    <v-progress-linear v-if="loading" indeterminate color="primary" aria-label="Загрузка покупок" class="mb-4" />
    <v-alert v-if="error" type="error" variant="tonal" class="mb-4">{{ error }} <v-btn variant="text" @click="load">Повторить</v-btn></v-alert>
    <v-alert v-if="historyError" type="error" variant="tonal" class="mb-4" role="alert">{{ historyError }}</v-alert>
    <v-alert v-if="storageError" type="warning" class="mb-4">Браузер не сохранил изменения. Скачайте список, чтобы не потерять его.</v-alert>
    <div v-if="!loading && !error && !plans.length" class="purchase-empty"><span class="purchase-empty__icon"><MpIcon name="bag" :size="44" /></span><span class="mp-overline">Сначала меню</span><h2>Одна неделя — основа месяца.</h2><p>Составьте меню. Здесь мы повторим его на выбранный период, посчитаем упаковки и распределим закупки.</p><v-btn to="/menu?new=1" color="primary">Составить меню</v-btn></div>
    <template v-if="selectedPlan && !loading && !error">
      <section class="provision-setup" aria-label="Период закупок">
        <div class="provision-setup__fields"><v-select v-model="selectedId" :items="planOptions" label="Повторять меню" hide-details @update:model-value="selectPlan"><template v-if="historyHasMore" #append-item><v-btn variant="text" block :loading="historyLoading" :disabled="historyLoading" @click.stop="loadMorePlans">Загрузить более ранние меню</v-btn></template></v-select><v-select v-model="options.horizon" :items="horizons" label="Период" hide-details @update:model-value="saveOptions" /><v-text-field v-model="options.start" type="date" label="Начать с" hide-details @change="saveOptions" /></div>
        <div class="provision-setup__rhythm"><v-checkbox v-model="options.freezer" label="Есть морозильник" hide-details @update:model-value="saveOptions" /><v-checkbox v-model="options.batch" label="Готовить заранее, когда возможно" hide-details @update:model-value="saveOptions" /><v-select v-if="selectedPlan.daysCount < 7" v-model="options.freeDay" :items="freeDayOptions" label="Свободный день недели" hide-details @update:model-value="saveOptions" /></div>
        <p>{{ dateLabel(safeOptions.start) }} — {{ dateLabel(dateAt(safeOptions.start, schedule.days - 1)) }} · {{ schedule.days }} дней · меню повторяется каждые 7 дней. Фасовки подобраны как ориентир и редактируются под ваш магазин.</p>
      </section>
      <v-alert v-if="incomplete || schedule.incomplete" type="warning" variant="tonal" class="mb-4">В исходном меню не хватает дней или состава блюд. Покупки и готовка рассчитаны только для сохранившихся ингредиентов. Составьте новое меню для полного плана.</v-alert>
      <div v-if="schedule.freeDays.length" class="provision-notice"><strong>{{ schedule.freeDays.length }} свободных дня без продуктов</strong><span>Они оставлены для ваших планов. Чтобы учесть питание и на эти дни, выберите выше, какой день меню повторять.</span></div>
      <section class="provision-overview"><div><span>Период</span><strong>{{ schedule.days }} <small>дней</small></strong><p>{{ schedule.days - schedule.freeDays.length }} с меню · {{ schedule.freeDays.length }} свободных</p></div><div><span>В магазин</span><strong>{{ shoppingTrips.length }} <small>походов</small></strong><p>Обычно два в неделю + пополнения</p></div><div><span>Закупка целиком</span><strong>{{ pricedSummary.unknown === pricedSummary.toBuy && pricedSummary.toBuy ? 'Без цен' : money(pricedSummary.total) + (pricedSummary.unknown ? ' + ?' : '') }}</strong><p>{{ pricedSummary.unknown ? `${pricedSummary.unknown} поз. ещё без цены` : 'По вашим ценам, без доставки' }}</p></div></section>
      <nav class="provision-views" aria-label="Покупки и приготовление"><button :class="{ active: view === 'list' }" :aria-pressed="view === 'list'" @click="view = 'list'">Список покупок</button><button :class="{ active: view === 'calendar' }" :aria-pressed="view === 'calendar'" @click="view = 'calendar'">Календарь готовки</button></nav>
      <template v-if="view === 'list'">
        <div class="provision-trip"><v-select v-model="tripDay" :items="tripOptions" label="Какую закупку показать" hide-details /><div><strong>{{ tripDay === -1 ? 'Итого на весь период' : `${dateLabel(dateAt(safeOptions.start, tripDay))} · ${tripDay === 0 ? 'Основная закупка' : 'Пополнение'}` }}</strong><p>{{ tripDay === -1 ? 'Сумма всех походов. Свежие продукты покупайте по датам, а не все сразу.' : 'Отмечайте купленное. Для свежих закрытых упаковок проверяйте срок до следующего похода.' }}</p></div></div>
        <div class="purchase-toolbar"><div class="purchase-tabs" role="group" aria-label="Какие покупки показывать"><button v-for="tab in purchaseTabs" :key="tab.value" :aria-pressed="filter === tab.value" :class="{ 'is-active': filter === tab.value }" @click="filter = tab.value">{{ tab.label }}<span>{{ tab.count }}</span></button></div><v-menu><template #activator="{ props }"><v-btn v-bind="props" variant="outlined" aria-label="Взять список с собой"><MpIcon name="download" :size="16" /><span class="purchase-export-label">Взять с собой</span></v-btn></template><v-list density="compact"><v-list-item @click="copyList">Копировать эту закупку</v-list-item><v-list-item @click="download('txt')">Скачать план закупок</v-list-item><v-list-item @click="download('csv')">Скачать эту закупку CSV</v-list-item><v-list-item @click="printList">Распечатать текущий список</v-list-item></v-list></v-menu></div>
        <p class="provision-progress" aria-live="polite">{{ displayedRows.filter(isDone).length }} из {{ displayedRows.length }} позиций готовы{{ tripDay === -1 ? ' за весь период' : ' к этой закупке' }}</p>
        <div v-if="!visibleRows.length" class="purchase-complete"><MpIcon name="check" :size="30" /><h3>{{ filter === 'remaining' ? 'На этот поход всё готово.' : 'Здесь пока пусто.' }}</h3><p>Купленные продукты и домашние запасы учтены.</p><button v-if="filter !== 'all'" @click="filter = 'all'">Показать весь список</button></div>
        <section v-for="group in groupedRows" :key="group.name" class="provision-aisle"><h2>{{ group.name }} <span>{{ group.rows.length }}</span></h2><div class="purchase-list">
          <article v-for="row in group.rows" :key="row.key" class="purchase-card" :class="{ 'shopping-done': isDone(row) }">
            <div class="purchase-card__head"><label v-if="row.buy && tripDay !== -1" class="purchase-check"><input type="checkbox" :checked="isDone(row)" :aria-label="`Куплено: ${row.settings.name}`" @change="toggleChecked(row)" /><span><MpIcon v-if="isDone(row)" name="check" :size="16" /></span></label><span v-else-if="!row.buy" class="purchase-home-check"><MpIcon name="check" :size="17" /></span><div class="purchase-card__title"><h3>{{ row.settings.name }}</h3><p>{{ !row.buy ? 'Покрыто запасом' : row.unit === 'шт.' && row.settings.packSize === 1 ? 'Поштучно' : row.packs !== null ? `${row.packs} уп. × ${quantityText(row.settings.packSize!, row.unit)}` : 'На вес · округлено вверх' }}</p><p v-if="row.settings.supply === 'freezer'">{{ safeOptions.freezer ? 'Часть на потом — сразу в морозильник' : 'Купить к приготовлению' }}</p></div><div class="purchase-card__amount"><strong>{{ row.buy ? quantityText(row.buy, row.unit) : 'Есть дома' }}</strong><span>{{ row.cost === null ? 'Цена не указана' : money(row.cost) }}</span></div><button class="mp-icon-button purchase-settings" :aria-label="`Настроить: ${row.settings.name}`" @click="edit(row)"><MpIcon name="sliders" :size="18" /></button></div>
            <p v-if="row.settings.note" class="purchase-note">{{ row.settings.note }}</p>
            <details class="purchase-details"><summary>Почему столько · блюда и остатки</summary><div class="purchase-card__numbers"><div><span>Нужно для еды</span><strong>{{ quantityText(row.needed, row.unit) }}</strong></div><div><span>{{ tripDay === -1 ? 'Начальный запас' : 'Учтено из запаса' }}</span><strong>{{ quantityText(row.settings.pantry, row.unit) }}</strong></div><div><span>Купить</span><strong>{{ quantityText(row.buy, row.unit) }}</strong></div><div><span>{{ tripDay === -1 ? 'Не распределено из запаса и покупок' : 'После приготовления' }}</span><strong>{{ quantityText(rowCarry(row), row.unit) }}</strong></div></div><p v-if="row.settings.yield !== 1" class="purchase-hint">Готовый продукт пересчитан в сырой: выход ×{{ row.settings.yield }}. Это приблизительная оценка, её можно изменить.</p><p v-if="row.settings.supply === 'fresh' || !safeOptions.freezer && row.settings.supply === 'freezer' || purchaseDefaults(row.source.name, row.source.unitType).afterOpening" class="purchase-hint">После вскрытия используйте по сроку на этикетке. В дальние закупки он автоматически не переносится: проверьте свежесть и при необходимости уточните запас.</p><div class="provision-uses"><strong>В меню за весь период · {{ (schedule.uses[row.key] || []).length }} использований</strong><ul><li v-for="(use, i) in schedule.uses[row.key]" :key="i"><span>{{ dateLabel(use.date) }} · {{ use.title }}</span><b>{{ quantityText(Math.round(use.amount * 10) / 10, use.unit) }}</b></li></ul></div><div class="purchase-links"><v-btn size="small" variant="tonal" @click="edit(row)">Запас, фасовка и цена</v-btn><v-btn v-if="row.settings.productUrl" :href="row.settings.productUrl" target="_blank" rel="noopener noreferrer" size="small" variant="text">Мой товар ↗</v-btn><v-btn v-for="shop in productSearchLinks(row.settings.name)" :key="shop.name" :href="shop.url" target="_blank" rel="noopener noreferrer" size="small" variant="text">{{ shop.name }} ↗</v-btn></div></details>
          </article></div></section>
      </template>
      <template v-else>
        <div class="provision-calendar-intro"><h2>Продукты → партия → порции.</h2><p>Опорные дни — первый и четвёртый день каждой недели. Блюда без хранения готовятся к подаче. Дальние порции готовим заранее только при возможности заморозки.</p></div>
        <div class="provision-week-tabs" role="group" aria-label="Неделя календаря"><button v-for="week in Math.ceil(schedule.days / 7)" :key="week" :class="{ active: calendarWeek === week - 1 }" :aria-pressed="calendarWeek === week - 1" @click="calendarWeek = week - 1">Неделя {{ week }}</button></div>
        <div class="provision-calendar"><article v-for="day in calendarDays" :key="day.index" class="provision-day"><header><span>{{ dayLabel(day.date) }}</span><h3>{{ dateLabel(day.date) }}</h3><small>День {{ day.index + 1 }}</small></header><div class="provision-day__body"><button v-if="day.trip?.rows.some(row => row.buy)" class="provision-store" @click="openTrip(day.index)"><MpIcon name="bag" :size="18" /><span>В магазин · {{ day.trip.rows.filter(row => row.buy).length }} позиций</span><span>Открыть список →</span></button><p v-if="day.free" class="provision-free">Свободный день. Еда не включена в расчёт.</p><p v-if="day.rawThaw.length" class="provision-thaw">Подготовить продукты к завтрашней готовке: {{ day.rawThaw.join(', ') }}. Нужную часть разморозить в холодильнике по инструкции на упаковке.</p><p v-for="portion in day.thaw" :key="portion.key" class="provision-thaw">Переложить в холодильник для размораживания: {{ portion.item.title }} · на {{ dateLabel(dateAt(day.date, 1)) }}</p><div v-for="task in day.tasks" :key="task.key" class="provision-task"><span class="mp-overline">{{ task.portions.length > 1 ? `Одна партия · порций: ${task.portions.length}` : task.portions[0]?.item.sourceType === 'product' ? 'Взять к приёму пищи' : task.info?.cookingMode === 'assembly' ? 'Собрать перед едой' : 'Приготовить' }}</span><h4>{{ task.title }}</h4><p>{{ task.portions.map(p => dateLabel(p.date) + (p.item.mealTitle ? ` · ${p.item.mealTitle}` : '')).join(' / ') }}</p><p v-if="task.frozen.length" class="provision-freeze">После охлаждения заморозить {{ task.frozen.length }} порц. Остальные — к ближайшим приёмам пищи.</p><p v-if="task.info?.batchNotes" class="provision-batch-note">{{ task.info.batchNotes }}</p><details><summary>Состав партии и распределение</summary><ul class="provision-ingredients"><li v-for="ing in task.ingredients" :key="purchaseKey(ing)"><span>{{ ing.name }}</span><b>{{ cookingAmount(ing) }}</b></li></ul><p>Это состав из сохранённого меню. Порции могут отличаться: делите готовую основу пропорционально исходному весу каждой порции, добавки — отдельно.</p><ul class="provision-ingredients"><li v-for="portion in task.portions" :key="portion.key"><span>{{ dateLabel(portion.date) }} · {{ portion.item.mealTitle }}</span><b>{{ portionShare(task, portion.key) }}% партии</b></li></ul><p v-if="task.info?.storageInstructions">{{ task.info.storageInstructions }}</p><NuxtLink v-if="task.recipeId" :to="`/recipes/${task.recipeId}`">Способ приготовления →</NuxtLink><p v-else-if="task.portions[0]?.item.sourceType !== 'product'">Исходный рецепт недоступен; состав меню сохранён.</p></details></div><p v-if="day.ready.length" class="provision-ready">Из приготовленного заранее: {{ day.ready.map(p => p.item.title).join(', ') }}. Разогрейте только нужные порции.</p></div></article></div>
        <div class="provision-storage"><strong>Охладить, подписать дату, убрать на хранение.</strong><p>Готовую еду убирайте в холодильник в течение 1–2 часов, рис — в течение часа. На дальние дни порции замораживаются, а не остаются в холодильнике. После размораживания используйте в течение 24 часов. Скоропортящиеся продукты покупайте с подходящим сроком годности; правила на этикетке имеют приоритет.</p><a href="https://www.food.gov.uk/safety-hygiene/chilling" target="_blank" rel="noopener noreferrer">Правила хранения FSA ↗</a></div>
      </template>
      <details class="purchase-help"><summary>Что учитывает план</summary><p>Недельное меню повторяется на выбранный период. Количество еды не увеличивается до упаковки: лишнее остаётся запасом. Стоимость учитывает реальные целые пачки в каждом походе. Консервы считаются по полезной массе без жидкости. Для продуктов в граммах размер пачки тоже задаётся в граммах.</p><p>Бакалея закупается на весь период. При включённом морозильнике мясо, рыба и хлеб тоже закупаются заранее. Свежие продукты распределяются по датам. Закрытые молочные упаковки выбирайте со сроком годности до следующего похода; открытые остатки учитываются отдельно. Если до готовки слишком долго, добавляется небольшой поход. Сроки переноса остатков — консервативная оценка для планирования, сверяйте их с этикеткой.</p><p>Календарь объединяет только одинаковые пропорции ингредиентов. Для старых меню шаги и хранение берутся из текущего рецепта, а количества — из сохранённого меню. Если меняли состав рецепта, сначала составьте новое меню.</p><p>Период, запасы, фасовки, цены и отметки сохраняются в этом браузере для аккаунта и меню. Это расчёт запасов: фактическое списание и синхронизация между устройствами пока не ведутся. Копирование и CSV включают весь выбранный поход; TXT — все походы по датам.</p></details>
    </template>
    <v-dialog v-model="editorOpen" max-width="620" scrollable>
      <v-card v-if="editing">
        <v-card-title class="purchase-dialog-title">Покупка: {{ editing.source.name }}</v-card-title>
        <v-card-text>
          <v-form id="purchase-form" @submit.prevent="saveEdit">
            <v-alert v-if="formError" type="error" class="mb-4" role="alert">{{ formError }}</v-alert>
            <v-text-field v-model="draft.name" label="Название товара для покупки" maxlength="160" hint="Можно указать марку или предпочтение. Состав меню не изменится." persistent-hint class="mb-3" />
            <v-text-field v-if="editing.source.unitType === 'gram'" v-model="draft.yield" label="Выход после приготовления" inputmode="decimal" hint="Готовый вес ÷ сырой. Например: 300 г из 100 г → 3. Без пересчёта → 1." persistent-hint class="mb-3" />
            <v-text-field v-model="draft.pantry" :label="`Запас в начале периода, ${editing.unit}`" inputmode="decimal" hint="Общий запас на весь период. Учитывайте срок годности и условия хранения." persistent-hint class="mb-3" />
            <v-checkbox v-if="editing.unit !== 'шт.'" v-model="draft.byWeight" label="Покупка на вес, округлять вверх до 50 г/мл" />
            <v-text-field v-model="draft.packSize" :label="`${draft.byWeight ? 'Количество для цены' : 'Размер упаковки'}, ${editing.unit}`" inputmode="decimal" hint="Фасовка — ориентир. Уточните по своей упаковке. Пусто — на вес или поштучно. Для консервов укажите массу без жидкости, для масла в граммах — массу, а не объём." persistent-hint class="mb-3" />
            <v-text-field v-model="draft.packPrice" :label="draft.byWeight ? 'Цена за указанное количество, ₽' : 'Цена одной упаковки, ₽'" inputmode="decimal" hint="Для цены за кг включите покупку на вес и укажите количество 1000 г. Пусто — цена неизвестна." persistent-hint class="mb-3" />
            <v-text-field v-model="draft.productUrl" label="Ссылка на выбранный товар" inputmode="url" maxlength="2048" hint="Вставьте HTTPS-ссылку на карточку товара из любого магазина. Цена и фасовка заполняются вручную." persistent-hint class="mb-3" />
            <v-select v-model="draft.supply" :items="supplyOptions" label="Как закупать этот продукт" hint="Свежие продукты распределяются по датам. Морозильник учитывается только при включённой опции выше." persistent-hint class="mb-3" />
            <v-textarea v-model="draft.note" label="Предпочтения и заметки" maxlength="500" rows="2" hint="Например: без сахара, любимая марка или вариант замены." persistent-hint />
          </v-form>
        </v-card-text>
        <v-card-actions class="purchase-dialog-actions"><v-btn variant="text" @click="resetDraft">По умолчанию</v-btn><v-spacer /><v-btn @click="editorOpen = false">Отмена</v-btn><v-btn color="primary" variant="flat" type="submit" form="purchase-form">Сохранить</v-btn></v-card-actions>
      </v-card>
    </v-dialog>
    <v-dialog v-model="copyFallback" max-width="650"><v-card><v-card-title>Список для копирования</v-card-title><v-card-text><v-textarea :model-value="exportText" readonly rows="14" label="Список закупки" /></v-card-text><v-card-actions><v-btn @click="copyFallback = false">Закрыть</v-btn></v-card-actions></v-card></v-dialog>
    <v-snackbar v-model="copied">Список скопирован</v-snackbar>
  </div>
</template>
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useApi, type MealPlan, type CookingInfo } from '~/composables/useApi'
import { useAuthStore } from '~/stores/auth'
import { readStorage, errorMessage } from '~/utils/storage'
import { planDateLabel, localDateKey } from '~/utils/plans'
import { normalizeProductUrl, productSearchLinks, defaultPurchase, normalizePurchase, purchaseKey, purchaseSummary, purchaseText, purchaseCsv, quantityText, type IngredientRow, type PurchaseRow, type PurchaseSettings } from '~/utils/purchases'
import { purchaseDefaults, type Supply } from '~/utils/purchase-defaults'
import { dateAt, normalizeOptions, planProvisions, type TripRow, type CookingTask } from '~/utils/provisions'
const api = useApi(), auth = useAuthStore(), route = useRoute(), router = useRouter()
const plans = ref<MealPlan[]>([]), selectedId = ref<number | null>(null), cooking = ref<Record<number, CookingInfo>>({})
const historyHasMore = ref(false), historyLoading = ref(false), historyError = ref('')
let historyOffset = 0
const loading = ref(false), incomplete = ref(false), error = ref(''), storageError = ref(false)
const checked = ref<string[]>([]), settings = ref<Record<string, PurchaseSettings>>({})
const options = ref(normalizeOptions({}, localDateKey()))
const selectedPlan = computed(() => plans.value.find(plan => plan.id === selectedId.value))
const safeOptions = computed(() => normalizeOptions(options.value, localDateKey(), selectedPlan.value?.daysCount))
const schedule = computed(() => planProvisions(selectedPlan.value || { daysCount: 6, items: [] }, cooking.value, safeOptions.value, settings.value))
const shoppingTrips = computed(() => schedule.value.trips.filter(trip => trip.rows.some(row => row.buy)))
const view = ref<'list' | 'calendar'>('list'), tripDay = ref(0), calendarWeek = ref(0)
const filter = ref<'all' | 'remaining' | 'done'>('all'), copied = ref(false), copyFallback = ref(false)
const editorOpen = ref(false), editing = ref<PurchaseRow | null>(null), formError = ref('')
const draft = ref({ name: '', yield: '1', pantry: '0', packSize: '', packPrice: '', byWeight: false, note: '', productUrl: '', supply: 'fresh' as Supply })
const horizons = [{ value: 'week', title: 'Неделя · 7 дней' }, { value: 'fortnight', title: 'Две недели' }, { value: 'fourWeeks', title: 'Четыре недели · 28 дней' }, { value: 'month', title: 'Месяц от даты начала' }]
const supplyOptions = [{ value: 'pantry', title: 'На весь период · бакалея' }, { value: 'fresh', title: 'Свежим · к ближайшей готовке' }, { value: 'freezer', title: 'На весь период, если есть морозильник' }]
const freeDayOptions = computed(() => [{ value: -1, title: 'Оставить свободным' }, ...Array.from({ length: Math.min(7, selectedPlan.value?.daysCount || 6) }, (_, day) => ({ value: day, title: `Повторять день ${day + 1}` }))])
const planOptions = computed(() => plans.value.map(plan => ({ value: plan.id, title: `${planDateLabel(plan)} · меню №${plan.id}` })))
const tripOptions = computed(() => [{ value: -1, title: 'Весь период · общий объём' }, ...schedule.value.trips.map(trip => ({ value: trip.day, title: `${dateLabel(trip.date)} · ${trip.rows.filter(row => row.buy).length} купить` }))])
const displayedRows = computed<PurchaseRow[]>(() => tripDay.value === -1 ? schedule.value.purchases : schedule.value.trips.find(trip => trip.day === tripDay.value)?.rows || [])
const pricedSummary = computed(() => purchaseSummary(schedule.value.purchases))
const isDone = (row: PurchaseRow) => {
  if (!row.buy) return true
  if ('checkKey' in row) return checked.value.includes((row as TripRow).checkKey)
  return schedule.value.trips.flatMap(trip => trip.rows).filter(item => item.key === row.key && item.buy).every(item => checked.value.includes(item.checkKey))
}
const visibleRows = computed(() => displayedRows.value.filter(row => filter.value === 'all' || (filter.value === 'done' ? isDone(row) : !isDone(row))))
const groupedRows = computed(() => {
  const groups = new Map<string, PurchaseRow[]>()
  for (const row of visibleRows.value) { const name = purchaseDefaults(row.source.name, row.source.unitType).aisle; groups.set(name, [...(groups.get(name) || []), row]) }
  return [...groups].map(([name, rows]) => ({ name, rows }))
})
const purchaseTabs = computed(() => [{ value: 'all' as const, label: 'Все', count: displayedRows.value.length }, { value: 'remaining' as const, label: 'Купить', count: displayedRows.value.filter(row => !isDone(row)).length }, { value: 'done' as const, label: 'Готово', count: displayedRows.value.filter(isDone).length }])
const calendarDays = computed(() => Array.from({ length: Math.max(0, Math.min(7, schedule.value.days - calendarWeek.value * 7)) }, (_, i) => {
  const index = calendarWeek.value * 7 + i
  return { index, date: dateAt(safeOptions.value.start, index), free: schedule.value.freeDays.includes(index), trip: schedule.value.trips.find(trip => trip.day === index), tasks: schedule.value.cookingTasks.filter(task => task.day === index), rawThaw: safeOptions.value.freezer ? [...new Set(schedule.value.cookingTasks.filter(task => task.day === index + 1).flatMap(task => task.ingredients).filter(row => normalizePurchase(row, settings.value[purchaseKey(row)]).supply === 'freezer').map(row => row.name))] : [], thaw: schedule.value.cookingTasks.flatMap(task => task.frozen).filter(portion => portion.day - 1 === index), ready: schedule.value.cookingTasks.filter(task => task.day < index).flatMap(task => task.portions).filter(portion => portion.day === index) }
}))
const dateLabel = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString('ru-RU', { day: 'numeric', month: 'short' })
const dayLabel = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString('ru-RU', { weekday: 'long' })
const money = (value: number) => quantityText(value, '₽')
const rowCarry = (row: PurchaseRow) => 'carry' in row ? (row as TripRow).carry : row.surplus
const cookingAmount = (row: IngredientRow) => quantityText(Math.round((row.unitType === 'gram' ? row.weight : row.quantity) * 10) / 10, row.unitType === 'gram' ? 'г' : row.unitType === 'ml' ? 'мл' : 'шт.')
const portionShare = (task: CookingTask, key: string) => {
  const total = task.ingredients.reduce((sum, row) => sum + row.weight, 0)
  const weight = task.portions.find(p => p.key === key)?.item.shoppingSnapshot?.reduce((sum, row) => sum + row.weight, 0) || 0
  return Math.round(weight / Math.max(total, 1) * 1000) / 10
}
const keyFor = (kind: string) => auth.user ? `provisions:v2:${auth.user.id}:${selectedId.value}:${kind}` : null
const settingsKey = () => auth.user ? `purchase-settings:v1:${auth.user.id}:${selectedId.value}` : null
const store = (key: string | null, value: unknown) => { try { if (!key) throw new Error('Account unavailable'); localStorage.setItem(key, JSON.stringify(value)) } catch { storageError.value = true } }
const parseStorage = (key: string | null, fallback: unknown): unknown => { try { return key ? JSON.parse(readStorage(key) || JSON.stringify(fallback)) : fallback } catch { return fallback } }
function saveOptions() { options.value = safeOptions.value; calendarWeek.value = 0; tripDay.value = schedule.value.trips[0]?.day ?? -1; store(keyFor('options'), options.value) }
function toggleChecked(row: PurchaseRow) { if (!('checkKey' in row)) return; const key = (row as TripRow).checkKey; checked.value = checked.value.includes(key) ? checked.value.filter(item => item !== key) : [...checked.value, key]; store(keyFor('checked'), checked.value) }
function openTrip(day: number) { tripDay.value = day; filter.value = 'all'; view.value = 'list' }
const exportTitle = computed(() => `Покупки · меню №${selectedId.value} · ${tripDay.value === -1 ? `${dateLabel(safeOptions.value.start)} — ${dateLabel(dateAt(safeOptions.value.start, schedule.value.days - 1))}` : dateLabel(dateAt(safeOptions.value.start, tripDay.value))}`)
const exportText = computed(() => purchaseText(displayedRows.value, exportTitle.value, displayedRows.value.filter(isDone).map(row => row.key)) + `\nСвободных дней без продуктов: ${schedule.value.freeDays.length}. Свежие продукты покупайте по датам календаря.`)
const printList = () => window.print()
function setDraft(value: PurchaseSettings) { draft.value = { ...value, yield: String(value.yield), pantry: String(value.pantry), packSize: value.packSize === null ? '' : String(value.packSize), packPrice: value.packPrice === null ? '' : String(value.packPrice) }; formError.value = '' }
function edit(row: PurchaseRow) { const total = schedule.value.purchases.find(item => item.key === row.key) || row; editing.value = total; setDraft(normalizePurchase(total.source, settings.value[total.key])); editorOpen.value = true }
function resetDraft() { if (editing.value) setDraft(defaultPurchase(editing.value.source)) }
function saveEdit() {
  if (!editing.value) return
  const parse = (text: string) => text.trim() ? Number(text.trim().replace(',', '.')) : NaN
  const value: PurchaseSettings = { ...draft.value, name: draft.value.name.trim(), yield: parse(draft.value.yield), pantry: parse(draft.value.pantry), packSize: draft.value.packSize.trim() ? parse(draft.value.packSize) : null, packPrice: draft.value.packPrice.trim() ? parse(draft.value.packPrice) : null, note: draft.value.note.trim(), productUrl: normalizeProductUrl(draft.value.productUrl) }
  if (draft.value.productUrl.trim() && !value.productUrl) { formError.value = 'Укажите HTTPS-ссылку на товар без логина и пароля или оставьте поле пустым.'; return }
  if (!value.name || value.name.length > 160) { formError.value = 'Укажите название товара (до 160 символов).'; return }
  if (!Number.isFinite(value.yield) || value.yield < 0.05 || value.yield > 20) { formError.value = 'Выход должен быть числом от 0,05 до 20.'; return }
  if (!Number.isFinite(value.pantry) || value.pantry < 0 || value.pantry > 1000000) { formError.value = 'Запас должен быть числом от 0 до 1 000 000.'; return }
  if (value.packSize !== null && (!Number.isFinite(value.packSize) || value.packSize < 0.01 || value.packSize > 1000000)) { formError.value = 'Укажите положительный размер упаковки до 1 000 000 или оставьте поле пустым.'; return }
  if (editing.value.unit === 'шт.' && (!Number.isInteger(value.pantry) || value.packSize !== null && !Number.isInteger(value.packSize))) { formError.value = 'Штуки и упаковки задаются целыми числами.'; return }
  if (value.packPrice !== null && (value.packSize === null || !Number.isFinite(value.packPrice) || value.packPrice < 0 || value.packPrice > 1000000)) { formError.value = 'Для цены нужен размер упаковки. Цена — от 0 до 1 000 000 ₽.'; return }
  settings.value[editing.value.key] = value
  store(settingsKey(), settings.value)
  // Only retain checks whose date, product and required purchase still match.
  const valid = new Set(schedule.value.trips.flatMap(trip => trip.rows.map(row => row.checkKey)))
  checked.value = checked.value.filter(key => valid.has(key)); store(keyFor('checked'), checked.value)
  editorOpen.value = false
}
async function copyList() { try { await navigator.clipboard.writeText(exportText.value); copied.value = true } catch { copyFallback.value = true } }
function download(format: 'txt' | 'csv') {
  const fullText = `План закупок · меню №${selectedId.value}\n${safeOptions.value.start} — ${dateAt(safeOptions.value.start, schedule.value.days - 1)}\nСвободных дней без продуктов: ${schedule.value.freeDays.length}\n\n` + schedule.value.trips.map(trip => purchaseText(trip.rows, dateLabel(trip.date), trip.rows.filter(isDone).map(row => row.key))).join('\n\n')
  const blob = new Blob([format === 'txt' ? fullText : purchaseCsv(displayedRows.value, displayedRows.value.filter(isDone).map(row => row.key))], { type: format === 'txt' ? 'text/plain;charset=utf-8' : 'text/csv;charset=utf-8' })
  const url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = `pokupki-menu-${selectedId.value}.${format}`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000)
}
let requestVersion = 0
async function selectPlan() {
  if (!selectedId.value) return
  const id = selectedId.value, version = ++requestVersion
  loading.value = true; error.value = ''; checked.value = []; settings.value = {}; cooking.value = {}; incomplete.value = false; filter.value = 'all'; editorOpen.value = false
  try {
    const result = await api.getShoppingList(id)
    if (version !== requestVersion) return
    cooking.value = result.cooking || {}; incomplete.value = result.incomplete
    const saved = parseStorage(settingsKey(), {})
    if (saved && typeof saved === 'object' && !Array.isArray(saved)) settings.value = Object.fromEntries(result.rows.map(row => {
      const old = (saved as Record<string, unknown>)[purchaseKey(row)]
      // Old defaults had no package. Adopt suggested packs while retaining pantry/prices.
      const migrated = old && typeof old === 'object' && !('supply' in old) && (old as PurchaseSettings).packSize == null ? { ...old, packSize: defaultPurchase(row).packSize, byWeight: defaultPurchase(row).byWeight } : old
      return [purchaseKey(row), normalizePurchase(row, migrated)]
    }))
    options.value = normalizeOptions(parseStorage(keyFor('options'), {}), localDateKey(), selectedPlan.value?.daysCount)
    const marks = parseStorage(keyFor('checked'), [])
    checked.value = Array.isArray(marks) ? marks.filter((key): key is string => typeof key === 'string') : []
    tripDay.value = schedule.value.trips[0]?.day ?? -1; calendarWeek.value = 0
    await router.replace({ query: { plan: String(id) } })
  } catch (e) { if (version === requestVersion) error.value = errorMessage(e) }
  finally { if (version === requestVersion) loading.value = false }
}
async function load() {
  loading.value = true; error.value = ''
  try { plans.value = await api.getMealPlans(); historyOffset = plans.value.length; historyHasMore.value = plans.value.length === 20; const id = Number(route.query.plan); if (id && !plans.value.some(plan => plan.id === id)) plans.value.unshift(await api.getMealPlan(id)); selectedId.value = id || plans.value[0]?.id || null; await selectPlan() }
  catch (e) { error.value = errorMessage(e) }
  finally { loading.value = false }
}
async function loadMorePlans() {
  if (historyLoading.value) return
  historyLoading.value = true; historyError.value = ''
  try {
    const items = await api.getMealPlans(historyOffset)
    historyOffset += items.length; historyHasMore.value = items.length === 20
    const existing = new Set(plans.value.map(plan => plan.id))
    plans.value.push(...items.filter(plan => !existing.has(plan.id)))
  } catch (e) { historyError.value = errorMessage(e) }
  finally { historyLoading.value = false }
}
watch(() => route.query.plan, async value => {
  const id = Number(value) || plans.value[0]?.id
  if (!id || id === selectedId.value) return
  const version = ++requestVersion
  loading.value = true; error.value = ''
  try {
    const plan = plans.value.find(plan => plan.id === id) || await api.getMealPlan(id)
    if (version !== requestVersion) return
    if ((Number(route.query.plan) || plans.value[0]?.id) !== id) { loading.value = false; return }
    if (!plans.value.some(item => item.id === id)) plans.value.push(plan)
    selectedId.value = id
    await selectPlan()
  } catch (e) { if (version === requestVersion) { error.value = errorMessage(e); loading.value = false } }
})
onMounted(load)
</script>
<style scoped>
.purchase-plan-bar { display: flex; gap: 20px; align-items: center; margin: 0 0 24px; }.purchase-plan-bar > .v-input { max-width: 390px; }.purchase-plan-bar > span { font-size: 11px; color: var(--text-secondary); }
.purchase-summary { display: grid; grid-template-columns: 1.1fr 1fr; gap: 34px; padding: 29px 32px; border: 1px solid #dce2cf; border-radius: 20px; background: #eef2e4; margin-bottom: 28px; }.purchase-summary h2 { font: 400 42px var(--font-display); color: var(--color-primary); margin: 7px 0 12px; }.purchase-summary h2 span { font: 12px var(--font-sans); color: var(--text-secondary); }.purchase-summary p { font-size: 11px; color: var(--text-secondary); }.purchase-summary__cost { border-left: 1px solid #d6dec7; padding-left: 34px; }.purchase-summary__cost h2 { font-size: 30px; margin: 12px 0 14px; }.purchase-summary__cost > span:last-child { display: block; font-size: 12px; color: var(--text-secondary); margin-top: 7px; }.purchase-progress { height: 5px; border-radius: 5px; background: #d9e0cc; max-width: 320px; overflow: hidden; margin-bottom: 11px; }.purchase-progress span { display: block; height: 100%; background: #6a8755; transition: width .2s; }
.purchase-toolbar { display: flex; justify-content: space-between; gap: 14px; align-items: center; margin-bottom: 18px; flex-wrap: wrap; }.purchase-tabs { display: flex; gap: 3px; padding: 4px; border: 1px solid var(--border-subtle); border-radius: 12px; background: #eef0e7; }.purchase-tabs button { padding: 8px 14px; color: var(--text-secondary); font-size: 12px; border-radius: 8px; }.purchase-tabs button.is-active { background: #fff; color: var(--color-primary); box-shadow: var(--shadow-sm); }.purchase-tabs button span { margin-left: 8px; font-size: 12px; color: var(--text-muted); }
.purchase-list { display: grid; gap: 9px; }.purchase-card { padding: 17px 21px; border: 1px solid var(--border-subtle); border-radius: 14px; background: #fff; break-inside: avoid; }.purchase-card__head { display: flex; align-items: center; gap: 16px; }.purchase-card__title { flex: 1; min-width: 0; overflow-wrap: anywhere; }.purchase-card__title h3 { font-size: 14px; font-weight: 500; }.purchase-card__title p { font-size: 12px; color: var(--text-secondary); margin-top: 3px; }.purchase-card__amount { text-align: right; min-width: 75px; }.purchase-card__amount strong { font-size: 14px; font-weight: 500; display: block; }.purchase-card__amount > span { display: block; font-size: 12px; color: var(--text-secondary); margin-top: 3px; }.purchase-settings { margin-right: -5px; }.purchase-check { position: relative; width: 24px; height: 24px; flex-shrink: 0; cursor: pointer; }.purchase-check input { position: absolute; inset: 0; opacity: 0; margin: 0; cursor: pointer; }.purchase-check > span { pointer-events: none; width: 24px; height: 24px; border: 1px solid #c5cdbb; border-radius: 7px; display: flex; align-items: center; justify-content: center; }.purchase-check input:checked + span { background: var(--color-primary); color: #fff; border-color: var(--color-primary); }.purchase-check input:focus-visible + span { outline: 2px solid var(--color-primary); outline-offset: 3px; }.purchase-home-check { width: 24px; height: 24px; flex-shrink: 0; display: flex; align-items: center; justify-content: center; border-radius: 7px; background: #eaf0e2; color: var(--text-secondary); }
.purchase-details { margin: 10px 0 0 40px; }.purchase-details summary { font-size: 12px; color: var(--text-muted); cursor: pointer; padding: 3px 0; }.purchase-details[open] { padding-top: 9px; border-top: 1px solid var(--border-subtle); margin-top: 15px; }.purchase-card__numbers { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 15px 0; }.purchase-card__numbers span { display: block; font-size: 12px; color: var(--text-secondary); }.purchase-card__numbers strong { display: block; overflow-wrap: anywhere; font-size: 13px; font-weight: 500; margin-top: 5px; }.purchase-hint { font-size: 11px; color: var(--text-secondary); margin-top: 10px; line-height: 1.7; }.purchase-links { display: flex; gap: 8px; flex-wrap: wrap; margin-top: 14px; }.purchase-note { white-space: pre-wrap; overflow-wrap: anywhere; margin: 10px 0 0 40px; font-size: 12px; color: var(--text-secondary); }.shopping-done { background: #f5f7f0; }.shopping-done h3 { text-decoration: line-through; color: var(--text-secondary); }.shopping-done .purchase-card__amount strong { color: var(--text-secondary); }
.purchase-help { margin-top: 25px; color: var(--text-secondary); font-size: 11px; line-height: 1.8; }.purchase-help summary { cursor: pointer; font-size: 12px; }.purchase-help p { margin-top: 12px; max-width: 760px; }.purchase-empty { text-align: center; border: 1px solid var(--border-subtle); border-radius: 22px; padding: 60px 24px; background: #fff; }.purchase-empty__icon { display: flex; align-items: center; justify-content: center; width: 100px; height: 100px; background: #edf2e2; color: var(--text-secondary); border-radius: 50%; margin: 0 auto 28px; }.purchase-empty h2 { font: 400 34px var(--font-display); margin: 15px 0; }.purchase-empty p { max-width: 380px; margin: 0 auto 24px; font-size: 13px; line-height: 1.8; color: var(--text-secondary); }.purchase-complete { text-align: center; padding: 40px 20px; border: 1px dashed var(--border-strong); border-radius: 16px; }.purchase-complete > svg { color: var(--text-secondary); }.purchase-complete h3 { font: 400 25px var(--font-display); margin: 12px 0; }.purchase-complete p { font-size: 12px; color: var(--text-secondary); }.purchase-complete button { margin-top: 20px; color: var(--color-primary); text-decoration: underline; font-size: 12px; }.purchase-dialog-title { white-space: normal; overflow-wrap: anywhere; padding-top: 20px; }.purchase-dialog-actions { flex-wrap: wrap; padding: 15px; }
@media(max-width: 600px) { .purchase-plan-bar { display: block; }.purchase-plan-bar > span { display: block; margin-top: 8px; }.purchase-plan-bar > .v-input { max-width: none; }.purchase-summary { grid-template-columns: 1fr 1fr; gap: 14px; padding: 20px; margin-bottom: 20px; }.purchase-summary h2 { font-size: 32px; }.purchase-summary__cost { padding-left: 14px; }.purchase-summary__cost h2 { font-size: 21px; }.purchase-summary .mp-overline { font-size: 12px; letter-spacing: 1px; }.purchase-summary p { font-size: 12px; }.purchase-summary__cost > span:last-child { display: none; }.purchase-toolbar { gap: 8px; flex-wrap: nowrap; }.purchase-export { min-width: 42px; padding-inline: 10px; }.purchase-export-label { display: none; }.purchase-tabs { flex: 1; }.purchase-tabs button { flex: 1; padding-inline: 10px; }.purchase-card { padding: 16px 13px; }.purchase-card__head { gap: 10px; }.purchase-card__title h3 { font-size: 12px; }.purchase-card__amount strong { font-size: 12px; }.purchase-settings { width: 28px; flex-shrink: 0; }.purchase-card__amount { min-width: 60px; }.purchase-card__numbers { grid-template-columns: repeat(2, 1fr); }.purchase-details, .purchase-note { margin-left: 34px; }.purchase-empty { padding: 40px 22px; }.purchase-empty h2 { font-size: 29px; } }
@media print { .purchase-toolbar, .purchase-links, .purchase-help, .purchase-plan-bar, .purchase-settings, .purchase-details { display: none; }.purchase-card { padding: 8px 12px; }.purchase-list { gap: 6px; }.purchase-summary { padding: 16px; margin-bottom: 15px; }.purchase-summary__cost > span:last-child { display: none; } }

.provision-setup { background: #fff; border: 1px solid var(--border-subtle); border-radius: 18px; padding: 24px; margin-bottom: 18px; }
.provision-setup__fields { display: grid; grid-template-columns: 1.4fr 1fr 1fr; gap: 16px; }
.provision-setup__rhythm { display: flex; align-items: center; flex-wrap: wrap; gap: 8px 24px; margin-top: 15px; }.provision-setup__rhythm > .v-input { flex: 1; min-width: 190px; }.provision-setup > p { font-size: 12px; color: var(--text-secondary); margin-top: 14px; line-height: 1.7; }
.provision-notice { display: flex; gap: 18px; padding: 16px 20px; border-left: 3px solid var(--color-honey); background: #f5f0e5; border-radius: 4px 12px 12px 4px; font-size: 12px; margin-bottom: 20px; }.provision-notice strong { flex-shrink: 0; }.provision-notice span { color: var(--text-secondary); }
.provision-overview { display: grid; grid-template-columns: repeat(3, 1fr); border: 1px solid #dce2cf; background: #eef2e4; border-radius: 20px; padding: 25px 28px; gap: 24px; margin-bottom: 28px; }.provision-overview > div + div { border-left: 1px solid #d6dec7; padding-left: 24px; }.provision-overview span { font-size: 12px; color: var(--text-secondary); }.provision-overview strong { display: block; font: 400 33px var(--font-display); color: var(--color-primary); margin: 6px 0; }.provision-overview small { font: 13px var(--font-sans); }.provision-overview p { font-size: 11px; color: var(--text-secondary); }
.provision-views { display: flex; gap: 24px; border-bottom: 1px solid var(--border-subtle); margin-bottom: 25px; }.provision-views button { padding: 12px 0 16px; font-size: 15px; border-bottom: 2px solid transparent; color: var(--text-secondary); }.provision-views button.active { border-color: var(--color-primary); color: var(--color-primary); }
.provision-trip { display: flex; align-items: center; gap: 24px; margin-bottom: 22px; }.provision-trip > .v-input { flex: 0 1 330px; }.provision-trip > div:last-child { flex: 1; }.provision-trip strong { font-size: 14px; font-weight: 500; }.provision-trip p { font-size: 12px; color: var(--text-secondary); margin-top: 5px; }.provision-progress { font-size: 11px; color: var(--text-secondary); margin: -5px 0 22px; }.provision-aisle { margin-bottom: 25px; }.provision-aisle > h2 { border-left: 3px solid var(--color-accent); padding: 7px 12px; background: var(--color-accent-soft); border-radius: 0 7px 7px 0; font-size: 13px; font-weight: 600; margin-bottom: 10px; }.provision-aisle > h2 span { font-size: 11px; color: var(--text-muted); margin-left: 7px; }.provision-uses { margin-top: 18px; font-size: 12px; }.provision-uses > strong { font-weight: 500; }.provision-uses ul { list-style: none; padding: 0; margin: 8px 0; max-height: 260px; overflow-y: auto; }.provision-uses li { display: flex; justify-content: space-between; gap: 15px; padding: 7px 0; border-bottom: 1px solid var(--border-subtle); color: var(--text-secondary); }.provision-uses b { white-space: nowrap; font-weight: 500; }
.provision-calendar-intro h2 { font: 400 27px var(--font-display); margin-bottom: 10px; }.provision-calendar-intro p { max-width: 750px; font-size: 13px; color: var(--text-secondary); line-height: 1.8; }.provision-week-tabs { display: flex; gap: 8px; flex-wrap: wrap; margin: 20px 0; }.provision-week-tabs button { padding: 9px 14px; border: 1px solid var(--border-subtle); border-radius: 20px; font-size: 12px; }.provision-week-tabs button.active { background: var(--color-primary); color: #fff; border-color: var(--color-primary); }.provision-calendar { display: grid; gap: 16px; }.provision-day { display: grid; grid-template-columns: 120px 1fr; border: 1px solid var(--border-subtle); border-radius: 16px; background: #fff; overflow: hidden; }.provision-day > header { background: #f1f3ea; padding: 22px 16px; }.provision-day header span, .provision-day header small { font-size: 11px; color: var(--text-secondary); }.provision-day h3 { font: 400 22px var(--font-display); margin: 6px 0; }.provision-day__body { padding: 20px 24px; min-width: 0; }.provision-store { display: flex; gap: 12px; align-items: center; width: 100%; padding: 12px; background: #edf2e4; border-radius: 8px; text-align: left; font-size: 12px; margin-bottom: 18px; }.provision-store > span:last-child { margin-left: auto; font-size: 11px; }.provision-task { padding: 16px 0; }.provision-task + .provision-task { border-top: 1px solid var(--border-subtle); }.provision-task .mp-overline { font-size: 12px; }.provision-task h4 { font-size: 15px; font-weight: 500; margin: 7px 0; }.provision-task p, .provision-task details { font-size: 12px; color: var(--text-secondary); line-height: 1.75; }.provision-task details { margin-top: 12px; }.provision-task summary { cursor: pointer; color: var(--color-primary); }.provision-task details > p { margin: 10px 0; }.provision-ingredients { list-style: none; padding: 0; margin: 12px 0; }.provision-ingredients li { display: flex; justify-content: space-between; gap: 16px; padding: 5px 0; }.provision-ingredients b { white-space: nowrap; font-weight: 500; }.provision-task .provision-freeze { color: #436276; margin-top: 8px; }.provision-batch-note { margin-top: 8px; }.provision-ready, .provision-free, .provision-thaw { padding: 10px 0; font-size: 12px; line-height: 1.8; color: var(--text-secondary); }.provision-thaw { color: #436276; }.provision-storage { background: #eef2e4; padding: 20px 24px; border-radius: 14px; margin-top: 24px; font-size: 12px; line-height: 1.8; }.provision-storage p { margin: 8px 0; color: var(--text-secondary); }
@media(max-width: 800px) { .provision-setup__fields { grid-template-columns: 1fr 1fr; }.provision-setup__fields > :first-child { grid-column: 1 / -1; }.provision-notice { display: block; }.provision-notice span { display: block; margin-top: 5px; }.provision-trip { align-items: stretch; flex-direction: column; gap: 12px; }.provision-trip > .v-input { flex-basis: auto; }.provision-overview { gap: 15px; padding: 20px; }.provision-overview > div + div { padding-left: 15px; }.provision-overview strong { font-size: 26px; } }
@media(max-width: 500px) { .provision-setup { padding: 18px 14px; }.provision-setup__fields { grid-template-columns: 1fr; }.provision-setup__rhythm { gap: 0; }.provision-setup__rhythm > .v-input { min-width: 100%; }.provision-overview { grid-template-columns: 1fr 1fr; gap: 16px; }.provision-overview > div:last-child { grid-column: 1 / -1; border-left: 0; border-top: 1px solid #d6dec7; padding: 12px 0 0; }.provision-overview > div:last-child strong { font-size: 22px; }.provision-views { gap: 18px; }.provision-views button { font-size: 13px; }.provision-day { grid-template-columns: 1fr; }.provision-day > header { display: flex; gap: 12px; padding: 12px 16px; align-items: center; }.provision-day h3 { font-size: 19px; margin: 0; }.provision-day header small { margin-left: auto; }.provision-day__body { padding: 12px 16px; }.provision-store { flex-wrap: wrap; }.provision-store > span:last-child { display: none; }.provision-uses li, .provision-ingredients li { font-size: 11px; }.purchase-card__title h3 { font-size: 13px; }.purchase-card__head { flex-wrap: wrap; }.purchase-card__title { min-width: 110px; }.purchase-card__amount { min-width: 65px; } }
@media print { .provision-setup, .provision-views, .provision-trip, .provision-week-tabs, .provision-notice { display: none; }.provision-day { break-inside: avoid; }.provision-overview { padding: 14px; } }
</style>
